SELECT u.user_id, u.user_name, COUNT(b.booking_id) AS total_bookings							
FROM users u																	
LEFT JOIN bookings b ON u.user_id = b.user_id
GROUP BY u.user_id, u.user_name;
-- Rank properties based on the total number of bookings
SELECT p.property_id, p.property_name, COUNT(b.booking_id) AS total_bookings,
	   RANK() OVER (ORDER BY COUNT(b.booking_id) DESC) AS booking_rank
FROM properties p
LEFT JOIN bookings b ON p.property_id = b.property_id
GROUP BY p.property_id, p.property_name;
-- Find the average rating for each property using the AVG function and GROUP BY clause.
SELECT p.property_id, p.property_name, AVG(r.rating) AS average_rating															
FROM properties p																	
LEFT JOIN reviews r ON p.property_id = r.property_id															
GROUP BY p.property_id, p.property_name;
-- Use a window function (SUM, AVG) to calculate the cumulative number of bookings for each	
-- property over time.
SELECT p.property_id, p.property_name, b.booking_date,
	   SUM(COUNT(b.booking_id)) OVER (PARTITION BY p.property_id ORDER BY b.booking_date) AS cumulative_bookings												
FROM properties p																	
LEFT JOIN bookings b ON p.property_id = b.property_id																																							
GROUP BY p.property_id, p.property_name, b.booking_date;
-- Find the maximum rating given to each property using the MAX function and GROUP BY clause.
SELECT p.property_id, p.property_name, MAX(r.rating) AS max_rating
FROM properties p
LEFT JOIN reviews r ON p.property_id = r.property_id
GROUP BY p.property_id, p.property_name;
-- Use a window function (MIN, MAX) to find the highest and lowest ratings for each property.
SELECT p.property_id, p.property_name, r.rating,
	   MAX(r.rating) OVER (PARTITION BY p.property_id) AS highest_rating,
	   MIN(r.rating) OVER (PARTITION BY p.property_id) AS lowest_rating
FROM properties p
LEFT JOIN reviews r ON p.property_id = r.property_id;
-- Find the total revenue generated by each property using the SUM function and GROUP BY clause.	
SELECT p.property_id, p.property_name, SUM(b.amount) AS total_revenue
FROM properties p
LEFT JOIN bookings b ON p.property_id = b.property_id
GROUP BY p.property_id, p.property_name;
-- Use a window function (SUM) to calculate the running total of revenue for each property over time.
SELECT p.property_id, p.property_name, b.booking_date,
	   SUM(SUM(b.amount)) OVER (PARTITION BY p.property_id ORDER BY b.booking_date) AS running_total_revenue
FROM properties p
LEFT JOIN bookings b ON p.property_id = b.property_id
GROUP BY p.property_id, p.property_name, b.booking_date;
-- Find the minimum booking amount for each user using the MIN function and GROUP BY clause.
SELECT u.user_id, u.user_name, MIN(b.amount) AS min_booking_amount
FROM users u
LEFT JOIN bookings b ON u.user_id = b.user_id
GROUP BY u.user_id, u.user_name;
-- Use a window function (MIN) to find the lowest booking amount for each user over time
SELECT u.user_id, u.user_name, b.booking_date,
	   MIN(b.amount) OVER (PARTITION BY u.user_id ORDER BY b.booking_date) AS lowest_booking_amount
FROM users u
LEFT JOIN bookings b ON u.user_id = b.user_id;	
GROUP BY u.user_id, u.user_name, b.booking_date;
-- Find the average booking amount for each user using the AVG function and GROUP BY clause.
SELECT u.user_id, u.user_name, AVG(b.amount) AS average_booking_amount
FROM users u	
LEFT JOIN bookings b ON u.user_id = b.user_id
GROUP BY u.user_id, u.user_name;
-- Use a window function (AVG) to calculate the average booking amount for each user over time.
SELECT u.user_id, u.user_name, b.booking_date,
	   AVG(b.amount) OVER (PARTITION BY u.user_id ORDER BY b.booking_date) AS average_booking_amount_over_time
FROM users u
LEFT JOIN bookings b ON u.user_id = b.user_id;
GROUP BY u.user_id, u.user_name, b.booking_date;
-- Find the total number of reviews for each property using the COUNT function and GROUP BY clause.	
SELECT p.property_id, p.property_name, COUNT(r.review_id) AS total_reviews	
FROM properties p
LEFT JOIN reviews r ON p.property_id = r.property_id
GROUP BY p.property_id, p.property_name;	
-- Use a window function (COUNT) to calculate the cumulative number of reviews for each property over time.	
SELECT p.property_id, p.property_name, r.review_date,
	   SUM(COUNT(r.review_id)) OVER (PARTITION BY p.property_id ORDER BY r.review_date) AS cumulative_reviews
FROM properties p
LEFT JOIN reviews r ON p.property_id = r.property_id
GROUP BY p.property_id, p.property_name, r.review_date;
-- Find the maximum booking amount for each property using the MAX function and GROUP BY clause.
SELECT p.property_id, p.property_name, MAX(b.amount) AS max_booking_amount
FROM properties p
LEFT JOIN bookings b ON p.property_id = b.property_id
GROUP BY p.property_id, p.property_name;
--window function (ROW_NUMBER, RANK) to rank properties based on the total number of bookings they have received.
SELECT p.property_id, p.property_name, COUNT(b.booking_id) AS total_bookings,
	   ROW_NUMBER() OVER (ORDER BY COUNT(b.booking_id) DESC) AS booking_row_number,
	   RANK() OVER (ORDER BY COUNT(b.booking_id) DESC) AS booking_rank
FROM properties p
LEFT JOIN bookings b ON p.property_id = b.property_id
GROUP BY p.property_id, p.property_name;